service:
  name: canary-bot

custom: ${file(./secrets.yml)}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-scheduler

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    BUCKET: ${self:custom.bucket}
    STAGE_URL: ${self:custom.stage-url}
    RECORD_KEY: ${self:custom.record-key}
    SLACK_HOOK: ${self:custom.slack-hook}
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  updateBuildRecordSchedule:
    handler: src/handler.updateBuildRecord
    events:
      - schedule: cron(0/1 * * * ? *)
  getCurrentBuildRecord:
    handler: src/handler.getCurrentBuildRecord
    events:
      - http:
          method: get
          path: buildRecord
  startPerformanceTest:
    handler: src/handler.startPerformanceTest
    events:
      - http:
          method: get
          path: performance/start
  
